apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: default
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
    spec:
      containers:
      - image: asia-docker.pkg.dev/peerpre-g42/peerprep/frontend
        imagePullPolicy: Always
        name: frontend
        ports:
        - containerPort: 3000