name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test-user-service:
    name: test user service
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      PSQL_USERNAME: ${{ secrets.PSQL_USERNAME }}
      PSQL_HOSTNAME: ${{ secrets.PSQL_HOSTNAME }}
      PSQL_PASSWORD: ${{ secrets.PSQL_PASSWORD }}
      PSQL_PORT: ${{ secrets.PSQL_PORT }}
  
  defaults:
    run:
      working-directory: ./user-service/

    steps:
      - name: CheckoutC Code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x 
      - name: Download Dependencies
        run: |
          npm install
      - run: npm test
